version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
  service:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/app/.env
    env_file:
      - .env
    depends_on:
      - db
