name: Deploy to AWS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build binary
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.0'
        run: make build
      - name: Install node modules
        uses: actions/setup-node@v1
        with:
          node-version: 17
        run: npm ci
      - name: Deploy Lambda
        uses: serverless/github-action@v3
        run: STAGE=production make deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          GROUP_CHAT_ID: ${{ secrets.GROUP_CHAT_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          BOT_NAME: ${{ secrets.BOT_NAME }}
